/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 43
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 28
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_EQ = 1,
  anon_sym_COMMA = 2,
  anon_sym_true = 3,
  anon_sym_false = 4,
  sym_number = 5,
  anon_sym_DQUOTE = 6,
  sym_string_content = 7,
  sym_escape_sequence = 8,
  anon_sym_LBRACE = 9,
  anon_sym_RBRACE = 10,
  sym_identifier = 11,
  anon_sym_DASH_DASH = 12,
  aux_sym_comment_token1 = 13,
  sym_source_file = 14,
  sym_statement = 15,
  sym__value = 16,
  sym_boolean = 17,
  sym_string = 18,
  aux_sym__string_content = 19,
  sym_table = 20,
  sym__array_table = 21,
  sym__obj_table = 22,
  sym_pair = 23,
  sym_comment = 24,
  aux_sym_source_file_repeat1 = 25,
  aux_sym__array_table_repeat1 = 26,
  aux_sym__obj_table_repeat1 = 27,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_EQ] = "=",
  [anon_sym_COMMA] = ",",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_number] = "number",
  [anon_sym_DQUOTE] = "\"",
  [sym_string_content] = "string_content",
  [sym_escape_sequence] = "escape_sequence",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_identifier] = "identifier",
  [anon_sym_DASH_DASH] = "comment_start",
  [aux_sym_comment_token1] = "comment_content",
  [sym_source_file] = "source_file",
  [sym_statement] = "statement",
  [sym__value] = "_value",
  [sym_boolean] = "boolean",
  [sym_string] = "string",
  [aux_sym__string_content] = "_string_content",
  [sym_table] = "table",
  [sym__array_table] = "_array_table",
  [sym__obj_table] = "_obj_table",
  [sym_pair] = "pair",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__array_table_repeat1] = "_array_table_repeat1",
  [aux_sym__obj_table_repeat1] = "_obj_table_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_number] = sym_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_string_content] = sym_string_content,
  [sym_escape_sequence] = sym_escape_sequence,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_identifier] = sym_identifier,
  [anon_sym_DASH_DASH] = anon_sym_DASH_DASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_source_file] = sym_source_file,
  [sym_statement] = sym_statement,
  [sym__value] = sym__value,
  [sym_boolean] = sym_boolean,
  [sym_string] = sym_string,
  [aux_sym__string_content] = aux_sym__string_content,
  [sym_table] = sym_table,
  [sym__array_table] = sym__array_table,
  [sym__obj_table] = sym__obj_table,
  [sym_pair] = sym_pair,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__array_table_repeat1] = aux_sym__array_table_repeat1,
  [aux_sym__obj_table_repeat1] = aux_sym__obj_table_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__string_content] = {
    .visible = false,
    .named = false,
  },
  [sym_table] = {
    .visible = true,
    .named = true,
  },
  [sym__array_table] = {
    .visible = false,
    .named = true,
  },
  [sym__obj_table] = {
    .visible = false,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__array_table_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__obj_table_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_content = 1,
  field_key = 2,
  field_name = 3,
  field_start = 4,
  field_value = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_content] = "content",
  [field_key] = "key",
  [field_name] = "name",
  [field_start] = "start",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_content, 1},
    {field_start, 0},
  [2] =
    {field_name, 0},
  [3] =
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
};

static const TSSymbol ts_supertype_symbols[SUPERTYPE_COUNT] = {
  sym__value,
};

static const TSMapSlice ts_supertype_map_slices[] = {
  [sym__value] = {.index = 0, .length = 4},
};

static const TSSymbol ts_supertype_map_entries[] = {
  [0] =
    sym_boolean,
    sym_number,
    sym_string,
    sym_table,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(22);
      ADVANCE_MAP(
        '"', 33,
        ',', 24,
        '-', 4,
        '.', 16,
        '0', 27,
        '=', 23,
        '\\', 15,
        'f', 5,
        't', 10,
        '{', 38,
        '}', 39,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(21);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(3);
      if (lookahead == '"') ADVANCE(33);
      if (lookahead == '-') ADVANCE(35);
      if (lookahead == '\\') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '"', 33,
        '-', 4,
        '.', 16,
        '0', 27,
        'f', 6,
        't', 11,
        '{', 38,
        '}', 39,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(33);
      if (lookahead == '-') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(45);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(9);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 9:
      if (lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == 'r') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 11:
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 12:
      if (lookahead == 's') ADVANCE(8);
      END_STATE();
    case 13:
      if (lookahead == 'u') ADVANCE(7);
      END_STATE();
    case 14:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 15:
      if (lookahead == '"' ||
          lookahead == '\'' ||
          ('[' <= lookahead && lookahead <= ']') ||
          lookahead == 'b' ||
          lookahead == 'f' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(37);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(29);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(31);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 21:
      if (eof) ADVANCE(22);
      ADVANCE_MAP(
        '"', 33,
        ',', 24,
        '-', 4,
        '.', 16,
        '0', 27,
        '=', 23,
        'f', 5,
        't', 10,
        '{', 38,
        '}', 39,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(21);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(30);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(14);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(18);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(30);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(19);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '-') ADVANCE(35);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(36);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '-') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_DASH_DASH);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_DASH_DASH);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(49);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '-') ADVANCE(48);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(47);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(49);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '-') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(49);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(49);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 47},
  [42] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(39),
    [sym_statement] = STATE(19),
    [sym__value] = STATE(16),
    [sym_boolean] = STATE(10),
    [sym_string] = STATE(10),
    [sym_table] = STATE(10),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_true] = ACTIONS(7),
    [anon_sym_false] = ACTIONS(7),
    [sym_number] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [sym_identifier] = ACTIONS(15),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym__value] = STATE(25),
    [sym_boolean] = STATE(10),
    [sym_string] = STATE(10),
    [sym_table] = STATE(10),
    [sym__array_table] = STATE(40),
    [sym__obj_table] = STATE(40),
    [sym_pair] = STATE(24),
    [sym_comment] = STATE(2),
    [anon_sym_true] = ACTIONS(7),
    [anon_sym_false] = ACTIONS(7),
    [sym_number] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym_statement] = STATE(19),
    [sym__value] = STATE(16),
    [sym_boolean] = STATE(10),
    [sym_string] = STATE(10),
    [sym_table] = STATE(10),
    [sym_comment] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(7),
    [anon_sym_false] = ACTIONS(7),
    [sym_number] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [sym_identifier] = ACTIONS(15),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
  [STATE(4)] = {
    [sym_statement] = STATE(19),
    [sym__value] = STATE(16),
    [sym_boolean] = STATE(10),
    [sym_string] = STATE(10),
    [sym_table] = STATE(10),
    [sym_comment] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(23),
    [anon_sym_true] = ACTIONS(25),
    [anon_sym_false] = ACTIONS(25),
    [sym_number] = ACTIONS(28),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(34),
    [sym_identifier] = ACTIONS(37),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(9), 1,
      sym_number,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(42), 1,
      anon_sym_RBRACE,
    STATE(5), 1,
      sym_comment,
    STATE(33), 1,
      sym__value,
    ACTIONS(40), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(10), 3,
      sym_boolean,
      sym_string,
      sym_table,
  [31] = 9,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(9), 1,
      sym_number,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(44), 1,
      anon_sym_RBRACE,
    STATE(6), 1,
      sym_comment,
    STATE(33), 1,
      sym__value,
    ACTIONS(40), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(10), 3,
      sym_boolean,
      sym_string,
      sym_table,
  [62] = 8,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(9), 1,
      sym_number,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    STATE(7), 1,
      sym_comment,
    STATE(33), 1,
      sym__value,
    ACTIONS(40), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(10), 3,
      sym_boolean,
      sym_string,
      sym_table,
  [90] = 8,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(9), 1,
      sym_number,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    STATE(8), 1,
      sym_comment,
    STATE(17), 1,
      sym__value,
    ACTIONS(40), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(10), 3,
      sym_boolean,
      sym_string,
      sym_table,
  [118] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(9), 1,
      sym_comment,
    ACTIONS(48), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(46), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_identifier,
  [138] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(10), 1,
      sym_comment,
    ACTIONS(52), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(50), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_identifier,
  [158] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(11), 1,
      sym_comment,
    ACTIONS(56), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(54), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_identifier,
  [178] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(12), 1,
      sym_comment,
    ACTIONS(60), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(58), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_identifier,
  [198] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(13), 1,
      sym_comment,
    ACTIONS(64), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(62), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_identifier,
  [218] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(14), 1,
      sym_comment,
    ACTIONS(68), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(66), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_identifier,
  [238] = 8,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(9), 1,
      sym_number,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    STATE(15), 1,
      sym_comment,
    STATE(35), 1,
      sym__value,
    ACTIONS(40), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(10), 3,
      sym_boolean,
      sym_string,
      sym_table,
  [266] = 5,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(72), 1,
      anon_sym_COMMA,
    STATE(16), 1,
      sym_comment,
    ACTIONS(74), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(70), 5,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      sym_identifier,
  [287] = 5,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(78), 1,
      anon_sym_COMMA,
    STATE(17), 1,
      sym_comment,
    ACTIONS(80), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(76), 5,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      sym_identifier,
  [308] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(18), 1,
      sym_comment,
    ACTIONS(84), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(82), 5,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      sym_identifier,
  [326] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(19), 1,
      sym_comment,
    ACTIONS(88), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(86), 5,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      sym_identifier,
  [344] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(20), 1,
      sym_comment,
    ACTIONS(92), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(90), 5,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      sym_identifier,
  [362] = 5,
    ACTIONS(94), 1,
      anon_sym_DQUOTE,
    ACTIONS(98), 1,
      anon_sym_DASH_DASH,
    STATE(21), 1,
      sym_comment,
    STATE(22), 1,
      aux_sym__string_content,
    ACTIONS(96), 2,
      sym_string_content,
      sym_escape_sequence,
  [379] = 4,
    ACTIONS(98), 1,
      anon_sym_DASH_DASH,
    ACTIONS(100), 1,
      anon_sym_DQUOTE,
    ACTIONS(102), 2,
      sym_string_content,
      sym_escape_sequence,
    STATE(22), 2,
      aux_sym__string_content,
      sym_comment,
  [394] = 5,
    ACTIONS(98), 1,
      anon_sym_DASH_DASH,
    ACTIONS(105), 1,
      anon_sym_DQUOTE,
    STATE(21), 1,
      aux_sym__string_content,
    STATE(23), 1,
      sym_comment,
    ACTIONS(96), 2,
      sym_string_content,
      sym_escape_sequence,
  [411] = 5,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(107), 1,
      anon_sym_COMMA,
    ACTIONS(109), 1,
      anon_sym_RBRACE,
    STATE(24), 1,
      sym_comment,
    STATE(29), 1,
      aux_sym__obj_table_repeat1,
  [427] = 5,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(111), 1,
      anon_sym_COMMA,
    ACTIONS(113), 1,
      anon_sym_RBRACE,
    STATE(25), 1,
      sym_comment,
    STATE(27), 1,
      aux_sym__array_table_repeat1,
  [443] = 4,
    ACTIONS(98), 1,
      anon_sym_DASH_DASH,
    ACTIONS(115), 1,
      anon_sym_DQUOTE,
    STATE(26), 1,
      sym_comment,
    ACTIONS(117), 2,
      sym_string_content,
      sym_escape_sequence,
  [457] = 5,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(44), 1,
      anon_sym_RBRACE,
    ACTIONS(119), 1,
      anon_sym_COMMA,
    STATE(27), 1,
      sym_comment,
    STATE(30), 1,
      aux_sym__array_table_repeat1,
  [473] = 5,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(121), 1,
      anon_sym_RBRACE,
    STATE(28), 1,
      sym_comment,
    STATE(34), 1,
      sym_pair,
  [489] = 5,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(121), 1,
      anon_sym_RBRACE,
    ACTIONS(123), 1,
      anon_sym_COMMA,
    STATE(29), 1,
      sym_comment,
    STATE(32), 1,
      aux_sym__obj_table_repeat1,
  [505] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(125), 1,
      anon_sym_COMMA,
    ACTIONS(128), 1,
      anon_sym_RBRACE,
    STATE(30), 2,
      sym_comment,
      aux_sym__array_table_repeat1,
  [519] = 5,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(130), 1,
      anon_sym_RBRACE,
    STATE(31), 1,
      sym_comment,
    STATE(34), 1,
      sym_pair,
  [535] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(132), 1,
      anon_sym_COMMA,
    ACTIONS(135), 1,
      anon_sym_RBRACE,
    STATE(32), 2,
      sym_comment,
      aux_sym__obj_table_repeat1,
  [549] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(33), 1,
      sym_comment,
    ACTIONS(128), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [560] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(34), 1,
      sym_comment,
    ACTIONS(135), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [571] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(35), 1,
      sym_comment,
    ACTIONS(137), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [582] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(19), 1,
      sym_identifier,
    STATE(34), 1,
      sym_pair,
    STATE(36), 1,
      sym_comment,
  [595] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(139), 1,
      anon_sym_EQ,
    STATE(37), 1,
      sym_comment,
  [605] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(141), 1,
      anon_sym_EQ,
    STATE(38), 1,
      sym_comment,
  [615] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(143), 1,
      ts_builtin_sym_end,
    STATE(39), 1,
      sym_comment,
  [625] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(145), 1,
      anon_sym_RBRACE,
    STATE(40), 1,
      sym_comment,
  [635] = 3,
    ACTIONS(98), 1,
      anon_sym_DASH_DASH,
    ACTIONS(147), 1,
      aux_sym_comment_token1,
    STATE(41), 1,
      sym_comment,
  [645] = 1,
    ACTIONS(149), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
  [SMALL_STATE(6)] = 31,
  [SMALL_STATE(7)] = 62,
  [SMALL_STATE(8)] = 90,
  [SMALL_STATE(9)] = 118,
  [SMALL_STATE(10)] = 138,
  [SMALL_STATE(11)] = 158,
  [SMALL_STATE(12)] = 178,
  [SMALL_STATE(13)] = 198,
  [SMALL_STATE(14)] = 218,
  [SMALL_STATE(15)] = 238,
  [SMALL_STATE(16)] = 266,
  [SMALL_STATE(17)] = 287,
  [SMALL_STATE(18)] = 308,
  [SMALL_STATE(19)] = 326,
  [SMALL_STATE(20)] = 344,
  [SMALL_STATE(21)] = 362,
  [SMALL_STATE(22)] = 379,
  [SMALL_STATE(23)] = 394,
  [SMALL_STATE(24)] = 411,
  [SMALL_STATE(25)] = 427,
  [SMALL_STATE(26)] = 443,
  [SMALL_STATE(27)] = 457,
  [SMALL_STATE(28)] = 473,
  [SMALL_STATE(29)] = 489,
  [SMALL_STATE(30)] = 505,
  [SMALL_STATE(31)] = 519,
  [SMALL_STATE(32)] = 535,
  [SMALL_STATE(33)] = 549,
  [SMALL_STATE(34)] = 560,
  [SMALL_STATE(35)] = 571,
  [SMALL_STATE(36)] = 582,
  [SMALL_STATE(37)] = 595,
  [SMALL_STATE(38)] = 605,
  [SMALL_STATE(39)] = 615,
  [SMALL_STATE(40)] = 625,
  [SMALL_STATE(41)] = 635,
  [SMALL_STATE(42)] = 645,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__array_table, 3, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__array_table, 2, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__value, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table, 2, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_table, 2, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table, 3, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_table, 3, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 3, 0, 2),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 3, 0, 2),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 2, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 2, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 4, 0, 2),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 4, 0, 2),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__string_content, 2, 0, 0),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__string_content, 2, 0, 0), SHIFT_REPEAT(26),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__obj_table, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__array_table, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__string_content, 1, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__string_content, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__obj_table, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [125] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__array_table_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__array_table_repeat1, 2, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__obj_table, 3, 0, 0),
  [132] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__obj_table_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__obj_table_repeat1, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3, 0, 3),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [143] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 1),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ltn(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .supertype_map_slices = ts_supertype_map_slices,
    .supertype_map_entries = ts_supertype_map_entries,
    .supertype_symbols = ts_supertype_symbols,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "ltn",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
