/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 42
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 32
#define ALIAS_COUNT 0
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACE = 1,
  anon_sym_COMMA = 2,
  anon_sym_RBRACE = 3,
  anon_sym_EQ = 4,
  sym_identifier = 5,
  anon_sym_DQUOTE = 6,
  sym__string_char = 7,
  sym_escape_sequence = 8,
  sym__decimal_integer = 9,
  sym__hexadecimal_integer = 10,
  aux_sym_double_token1 = 11,
  aux_sym_double_token2 = 12,
  anon_sym_true = 13,
  anon_sym_false = 14,
  sym_nil = 15,
  anon_sym_DASH_DASH = 16,
  aux_sym_comment_token1 = 17,
  sym_source = 18,
  sym__value = 19,
  sym_map_table = 20,
  sym_pair = 21,
  sym_array_table = 22,
  sym_string = 23,
  sym_number = 24,
  sym_integer = 25,
  sym_double = 26,
  sym_boolean = 27,
  sym_comment = 28,
  aux_sym_map_table_repeat1 = 29,
  aux_sym_array_table_repeat1 = 30,
  aux_sym_string_repeat1 = 31,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_EQ] = "=",
  [sym_identifier] = "identifier",
  [anon_sym_DQUOTE] = "\"",
  [sym__string_char] = "_string_char",
  [sym_escape_sequence] = "escape_sequence",
  [sym__decimal_integer] = "_decimal_integer",
  [sym__hexadecimal_integer] = "_hexadecimal_integer",
  [aux_sym_double_token1] = "double_token1",
  [aux_sym_double_token2] = "double_token2",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_nil] = "nil",
  [anon_sym_DASH_DASH] = "--",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_source] = "source",
  [sym__value] = "_value",
  [sym_map_table] = "map_table",
  [sym_pair] = "pair",
  [sym_array_table] = "array_table",
  [sym_string] = "string",
  [sym_number] = "number",
  [sym_integer] = "integer",
  [sym_double] = "double",
  [sym_boolean] = "boolean",
  [sym_comment] = "comment",
  [aux_sym_map_table_repeat1] = "map_table_repeat1",
  [aux_sym_array_table_repeat1] = "array_table_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_identifier] = sym_identifier,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym__string_char] = sym__string_char,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym__decimal_integer] = sym__decimal_integer,
  [sym__hexadecimal_integer] = sym__hexadecimal_integer,
  [aux_sym_double_token1] = aux_sym_double_token1,
  [aux_sym_double_token2] = aux_sym_double_token2,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_nil] = sym_nil,
  [anon_sym_DASH_DASH] = anon_sym_DASH_DASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_source] = sym_source,
  [sym__value] = sym__value,
  [sym_map_table] = sym_map_table,
  [sym_pair] = sym_pair,
  [sym_array_table] = sym_array_table,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [sym_integer] = sym_integer,
  [sym_double] = sym_double,
  [sym_boolean] = sym_boolean,
  [sym_comment] = sym_comment,
  [aux_sym_map_table_repeat1] = aux_sym_map_table_repeat1,
  [aux_sym_array_table_repeat1] = aux_sym_array_table_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym__string_char] = {
    .visible = false,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym__decimal_integer] = {
    .visible = false,
    .named = true,
  },
  [sym__hexadecimal_integer] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_double_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_double_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_nil] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_map_table] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_array_table] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_double] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_map_table_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_table_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '"', 28,
        ',', 18,
        '-', 4,
        '0', 32,
        '=', 20,
        '\\', 9,
        'f', 6,
        'n', 7,
        't', 8,
        '{', 17,
        '}', 19,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(15);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '"') ADVANCE(28);
      if (lookahead == '-') ADVANCE(30);
      if (lookahead == '\\') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(28);
      if (lookahead == '-') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(42);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(3);
      if (lookahead == '}') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 7:
      if (lookahead == 'i') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 8:
      if (lookahead == 'r') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 9:
      ADVANCE_MAP(
        '"', 31,
        '/', 31,
        '\\', 31,
        'b', 31,
        'f', 31,
        'n', 31,
        'r', 31,
        't', 31,
      );
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(35);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 15:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '"', 28,
        ',', 18,
        '-', 4,
        '0', 32,
        '=', 20,
        'f', 6,
        'n', 7,
        't', 8,
        '{', 17,
        '}', 19,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(15);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym__string_char);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym__string_char);
      if (lookahead == '-') ADVANCE(42);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym__decimal_integer);
      if (lookahead == '.') ADVANCE(10);
      if (lookahead == 'x') ADVANCE(13);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym__decimal_integer);
      if (lookahead == '.') ADVANCE(10);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym__decimal_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym__hexadecimal_integer);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_double_token1);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_double_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_double_token2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_nil);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_DASH_DASH);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_DASH_DASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(46);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '-') ADVANCE(45);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(46);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '-') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(46);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 5},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 5},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 5},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 44},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym__decimal_integer] = ACTIONS(1),
    [sym__hexadecimal_integer] = ACTIONS(1),
    [aux_sym_double_token1] = ACTIONS(1),
    [aux_sym_double_token2] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_nil] = ACTIONS(1),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source] = STATE(37),
    [sym__value] = STATE(40),
    [sym_map_table] = STATE(18),
    [sym_array_table] = STATE(18),
    [sym_string] = STATE(18),
    [sym_number] = STATE(18),
    [sym_integer] = STATE(31),
    [sym_double] = STATE(31),
    [sym_boolean] = STATE(18),
    [sym_comment] = STATE(1),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(7),
    [sym__decimal_integer] = ACTIONS(9),
    [sym__hexadecimal_integer] = ACTIONS(11),
    [aux_sym_double_token1] = ACTIONS(13),
    [aux_sym_double_token2] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_nil] = ACTIONS(19),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym__value] = STATE(15),
    [sym_map_table] = STATE(18),
    [sym_pair] = STATE(16),
    [sym_array_table] = STATE(18),
    [sym_string] = STATE(18),
    [sym_number] = STATE(18),
    [sym_integer] = STATE(31),
    [sym_double] = STATE(31),
    [sym_boolean] = STATE(18),
    [sym_comment] = STATE(2),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_RBRACE] = ACTIONS(21),
    [sym_identifier] = ACTIONS(23),
    [anon_sym_DQUOTE] = ACTIONS(7),
    [sym__decimal_integer] = ACTIONS(9),
    [sym__hexadecimal_integer] = ACTIONS(11),
    [aux_sym_double_token1] = ACTIONS(13),
    [aux_sym_double_token2] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(25),
    [anon_sym_false] = ACTIONS(25),
    [sym_nil] = ACTIONS(27),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym__value] = STATE(34),
    [sym_map_table] = STATE(18),
    [sym_array_table] = STATE(18),
    [sym_string] = STATE(18),
    [sym_number] = STATE(18),
    [sym_integer] = STATE(31),
    [sym_double] = STATE(31),
    [sym_boolean] = STATE(18),
    [sym_comment] = STATE(3),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_RBRACE] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(7),
    [sym__decimal_integer] = ACTIONS(9),
    [sym__hexadecimal_integer] = ACTIONS(11),
    [aux_sym_double_token1] = ACTIONS(13),
    [aux_sym_double_token2] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_nil] = ACTIONS(19),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
  [STATE(4)] = {
    [sym__value] = STATE(34),
    [sym_map_table] = STATE(18),
    [sym_array_table] = STATE(18),
    [sym_string] = STATE(18),
    [sym_number] = STATE(18),
    [sym_integer] = STATE(31),
    [sym_double] = STATE(31),
    [sym_boolean] = STATE(18),
    [sym_comment] = STATE(4),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_RBRACE] = ACTIONS(31),
    [anon_sym_DQUOTE] = ACTIONS(7),
    [sym__decimal_integer] = ACTIONS(9),
    [sym__hexadecimal_integer] = ACTIONS(11),
    [aux_sym_double_token1] = ACTIONS(13),
    [aux_sym_double_token2] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_nil] = ACTIONS(19),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
  [STATE(5)] = {
    [sym__value] = STATE(35),
    [sym_map_table] = STATE(18),
    [sym_array_table] = STATE(18),
    [sym_string] = STATE(18),
    [sym_number] = STATE(18),
    [sym_integer] = STATE(31),
    [sym_double] = STATE(31),
    [sym_boolean] = STATE(18),
    [sym_comment] = STATE(5),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(7),
    [sym__decimal_integer] = ACTIONS(9),
    [sym__hexadecimal_integer] = ACTIONS(11),
    [aux_sym_double_token1] = ACTIONS(13),
    [aux_sym_double_token2] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_nil] = ACTIONS(19),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
  [STATE(6)] = {
    [sym__value] = STATE(34),
    [sym_map_table] = STATE(18),
    [sym_array_table] = STATE(18),
    [sym_string] = STATE(18),
    [sym_number] = STATE(18),
    [sym_integer] = STATE(31),
    [sym_double] = STATE(31),
    [sym_boolean] = STATE(18),
    [sym_comment] = STATE(6),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(7),
    [sym__decimal_integer] = ACTIONS(9),
    [sym__hexadecimal_integer] = ACTIONS(11),
    [aux_sym_double_token1] = ACTIONS(13),
    [aux_sym_double_token2] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_nil] = ACTIONS(19),
    [anon_sym_DASH_DASH] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(33), 1,
      anon_sym_DQUOTE,
    ACTIONS(35), 1,
      sym__string_char,
    ACTIONS(37), 1,
      sym_escape_sequence,
    ACTIONS(39), 1,
      anon_sym_DASH_DASH,
    STATE(7), 1,
      sym_comment,
    STATE(9), 1,
      aux_sym_string_repeat1,
  [19] = 6,
    ACTIONS(35), 1,
      sym__string_char,
    ACTIONS(37), 1,
      sym_escape_sequence,
    ACTIONS(39), 1,
      anon_sym_DASH_DASH,
    ACTIONS(41), 1,
      anon_sym_DQUOTE,
    STATE(7), 1,
      aux_sym_string_repeat1,
    STATE(8), 1,
      sym_comment,
  [38] = 5,
    ACTIONS(39), 1,
      anon_sym_DASH_DASH,
    ACTIONS(43), 1,
      anon_sym_DQUOTE,
    ACTIONS(45), 1,
      sym__string_char,
    ACTIONS(48), 1,
      sym_escape_sequence,
    STATE(9), 2,
      sym_comment,
      aux_sym_string_repeat1,
  [55] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(10), 1,
      sym_comment,
    ACTIONS(51), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [67] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(11), 1,
      sym_comment,
    ACTIONS(53), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [79] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(12), 1,
      sym_comment,
    ACTIONS(55), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [91] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(13), 1,
      sym_comment,
    ACTIONS(57), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [103] = 4,
    ACTIONS(39), 1,
      anon_sym_DASH_DASH,
    ACTIONS(61), 1,
      sym_escape_sequence,
    STATE(14), 1,
      sym_comment,
    ACTIONS(59), 2,
      anon_sym_DQUOTE,
      sym__string_char,
  [117] = 5,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(63), 1,
      anon_sym_COMMA,
    ACTIONS(65), 1,
      anon_sym_RBRACE,
    STATE(15), 1,
      sym_comment,
    STATE(17), 1,
      aux_sym_array_table_repeat1,
  [133] = 5,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(67), 1,
      anon_sym_COMMA,
    ACTIONS(69), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      sym_comment,
    STATE(22), 1,
      aux_sym_map_table_repeat1,
  [149] = 5,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(29), 1,
      anon_sym_RBRACE,
    ACTIONS(71), 1,
      anon_sym_COMMA,
    STATE(17), 1,
      sym_comment,
    STATE(24), 1,
      aux_sym_array_table_repeat1,
  [165] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(18), 1,
      sym_comment,
    ACTIONS(73), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [177] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(19), 1,
      sym_comment,
    ACTIONS(75), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [189] = 5,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(77), 1,
      anon_sym_RBRACE,
    ACTIONS(79), 1,
      sym_identifier,
    STATE(20), 1,
      sym_comment,
    STATE(33), 1,
      sym_pair,
  [205] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(21), 1,
      sym_comment,
    ACTIONS(81), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [217] = 5,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(77), 1,
      anon_sym_RBRACE,
    ACTIONS(83), 1,
      anon_sym_COMMA,
    STATE(22), 1,
      sym_comment,
    STATE(27), 1,
      aux_sym_map_table_repeat1,
  [233] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(23), 1,
      sym_comment,
    ACTIONS(85), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [245] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(87), 1,
      anon_sym_COMMA,
    ACTIONS(90), 1,
      anon_sym_RBRACE,
    STATE(24), 2,
      sym_comment,
      aux_sym_array_table_repeat1,
  [259] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(25), 1,
      sym_comment,
    ACTIONS(92), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [271] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(26), 1,
      sym_comment,
    ACTIONS(94), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [283] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(96), 1,
      anon_sym_COMMA,
    ACTIONS(99), 1,
      anon_sym_RBRACE,
    STATE(27), 2,
      sym_comment,
      aux_sym_map_table_repeat1,
  [297] = 5,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(79), 1,
      sym_identifier,
    ACTIONS(101), 1,
      anon_sym_RBRACE,
    STATE(28), 1,
      sym_comment,
    STATE(33), 1,
      sym_pair,
  [313] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(29), 1,
      sym_comment,
    ACTIONS(103), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [325] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(30), 1,
      sym_comment,
    ACTIONS(105), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [337] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(31), 1,
      sym_comment,
    ACTIONS(107), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [349] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(32), 1,
      sym_comment,
    ACTIONS(109), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [361] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(33), 1,
      sym_comment,
    ACTIONS(99), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [372] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(34), 1,
      sym_comment,
    ACTIONS(90), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [383] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    STATE(35), 1,
      sym_comment,
    ACTIONS(111), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [394] = 4,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(79), 1,
      sym_identifier,
    STATE(33), 1,
      sym_pair,
    STATE(36), 1,
      sym_comment,
  [407] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(113), 1,
      ts_builtin_sym_end,
    STATE(37), 1,
      sym_comment,
  [417] = 3,
    ACTIONS(39), 1,
      anon_sym_DASH_DASH,
    ACTIONS(115), 1,
      aux_sym_comment_token1,
    STATE(38), 1,
      sym_comment,
  [427] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(117), 1,
      anon_sym_EQ,
    STATE(39), 1,
      sym_comment,
  [437] = 3,
    ACTIONS(3), 1,
      anon_sym_DASH_DASH,
    ACTIONS(119), 1,
      ts_builtin_sym_end,
    STATE(40), 1,
      sym_comment,
  [447] = 1,
    ACTIONS(121), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 19,
  [SMALL_STATE(9)] = 38,
  [SMALL_STATE(10)] = 55,
  [SMALL_STATE(11)] = 67,
  [SMALL_STATE(12)] = 79,
  [SMALL_STATE(13)] = 91,
  [SMALL_STATE(14)] = 103,
  [SMALL_STATE(15)] = 117,
  [SMALL_STATE(16)] = 133,
  [SMALL_STATE(17)] = 149,
  [SMALL_STATE(18)] = 165,
  [SMALL_STATE(19)] = 177,
  [SMALL_STATE(20)] = 189,
  [SMALL_STATE(21)] = 205,
  [SMALL_STATE(22)] = 217,
  [SMALL_STATE(23)] = 233,
  [SMALL_STATE(24)] = 245,
  [SMALL_STATE(25)] = 259,
  [SMALL_STATE(26)] = 271,
  [SMALL_STATE(27)] = 283,
  [SMALL_STATE(28)] = 297,
  [SMALL_STATE(29)] = 313,
  [SMALL_STATE(30)] = 325,
  [SMALL_STATE(31)] = 337,
  [SMALL_STATE(32)] = 349,
  [SMALL_STATE(33)] = 361,
  [SMALL_STATE(34)] = 372,
  [SMALL_STATE(35)] = 383,
  [SMALL_STATE(36)] = 394,
  [SMALL_STATE(37)] = 407,
  [SMALL_STATE(38)] = 417,
  [SMALL_STATE(39)] = 427,
  [SMALL_STATE(40)] = 437,
  [SMALL_STATE(41)] = 447,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_table, 3, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_table, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_table, 3, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_table_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_table_repeat1, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer, 1, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_table, 4, 0, 0),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_table_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_map_table_repeat1, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_table, 4, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_table, 5, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_table, 5, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3, 0, 1),
  [113] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ltn(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "ltn",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
